export const boxesClassList = [
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes green star",
  "boxes green star",
  "boxes star",
  "boxes green star",
  "boxes",
  "boxes",
  "boxes green star",
  "boxes",
  "boxes",
  "boxes green star",
  "boxes",
  "boxes",
  "boxes green star",
  "boxes",
  "boxes",
  "boxes red star",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes star",
  "boxes",
  "boxes",
  "boxes",
  "boxes red star",
  "boxes red star",
  "boxes red star",
  "boxes red star",
  "boxes red star",
  "boxes yellow star",
  "boxes yellow star",
  "boxes yellow star",
  "boxes yellow star",
  "boxes yellow star",
  "boxes",
  "boxes",
  "boxes",
  "boxes star",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
  "boxes yellow star",
  "boxes",
  "boxes",
  "boxes blue star",
  "boxes",
  "boxes",
  "boxes blue star",
  "boxes",
  "boxes",
  "boxes blue star",
  "boxes",
  "boxes",
  "boxes blue star",
  "boxes star",
  "boxes blue star",
  "boxes blue star",
  "boxes",
  "boxes",
  "boxes",
  "boxes",
];

export const STARBOXINDEX = boxesClassList.reduce((arr, val, index) => {
  if (val.split(" ").includes("star")) arr.push(index);
  return arr;
}, []);
