# Generated by Django 4.0.5 on 2022-06-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=1000)),
                ('red', models.CharField(max_length=255)),
                ('green', models.CharField(max_length=255)),
                ('yellow', models.CharField(max_length=255)),
                ('blue', models.CharField(max_length=255)),
            ],
        ),
    ]
